vBlogger.Web/Controllers/PostController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using vBlogger.Models;
using vBlogger.Web.AppSettings;
using vBlogger.Web.HttpClient;
using vBlogger.Web.Models;

namespace vBlogger.Web.Controllers
{
	public class PostController : Controller
	{
		private readonly IMapper _mapper;
		private readonly AppSetting _postsSettings;
		private readonly IPostHttpClient _postHttpClient;
		private readonly IHostingEnvironment _hostingEnvironment;

		public PostController(AppSetting postsSettings, IMapper mapper, IPostHttpClient postHttpClient, IHostingEnvironment environment)
		{
			_mapper = mapper;
			_postsSettings = postsSettings;
			_postHttpClient = postHttpClient;
			_hostingEnvironment = environment;
		}

		public IActionResult Index()
		{
			var postsModel = new List<PostViewModel>();
			return View(postsModel);
		}

		[HttpGet]
		public async Task<IActionResult> LoadPost(bool loadMore = false)
		{
			var postsModel = new List<PostViewModel>();

			var feedSize = _postsSettings.FeedSize;
			if (loadMore)
			{
				feedSize += _postsSettings.FeedSize;
			}
			var posts = await _postHttpClient.GetPosts(feedSize);
			if (posts.Any())
			{
				postsModel = _mapper.Map<List<PostViewModel>>(posts);
			}

			return PartialView("_PostsPartial", postsModel);
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(IFormFile picture, PostViewModel model)
		{
			var post = _mapper.Map<PostDto>(model);
			post.Tags = AddTags(post);
			post.ImageUrl = await GetImageUrl(picture);
			post.Author = User.Identity.Name;

			var created = await _postHttpClient.Create(post);
			return RedirectToAction("Manage");
		}

		public async Task<IActionResult> Manage()
		{
			var posts = await _postHttpClient.GetPosts(0);
			var postsModel = _mapper.Map<List<PostViewModel>>(posts);

			return View(postsModel);
		}

		public async Task<IActionResult> Edit(int id)
		{
			var post = await _postHttpClient.GetPostById(id);
			post.TagsString = string.Join(",", post.Tags.Select(x => x.Title));

			var postModel = _mapper.Map<PostViewModel>(post);
			return View(postModel);
		}

		public async Task<IActionResult> Details(int id)
		{
			var post = await _postHttpClient.GetPostById(id);
			post.TagsString = string.Join(",", post.Tags.Select(x => x.Title));

			var postModel = _mapper.Map<PostViewModel>(post);
			return View(postModel);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(IFormFile picture, PostViewModel model)
		{
			var post = _mapper.Map<PostDto>(model);
			post.Tags = AddTags(post);
			post.ImageUrl = await GetImageUrl(picture);

			var updated = await _postHttpClient.Update(post);
			return RedirectToAction("Manage");
		}

		public async Task<IActionResult> Delete(int id)
		{
			var deleted = await _postHttpClient.Delete(id);
			return RedirectToAction("Manage");
		}

		private async Task<string> GetImageUrl(IFormFile picture)
		{
			var uploads = Path.Combine(_hostingEnvironment.WebRootPath, _postsSettings.ImagesFolder);
			var filePath = Path.Combine(uploads, picture.FileName);
			using (var fileStream = new FileStream(filePath, FileMode.Create))
			{
				await picture.CopyToAsync(fileStream);
			}
			return $"/{_postsSettings.ImagesFolder}/{picture.FileName}";
		}

		private IEnumerable<TagDto> AddTags(PostDto post)
		{
			return post.TagsString?.Split(',').ToList().Select(x => new TagDto { Title = x }).ToList();
		}
	}
}

vBlogger.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - vBlogger</title>

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
			  crossorigin="anonymous"
			  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
	</environment>
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<div class="container-fluid">
			<nav style="background-color: #E2F2F1 !important" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
				<a class="navbar-brand" asp-area=""  asp-controller="Post" asp-action="Index">
					<img src="/images/logo.png" />
				</a>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="float: right">
					<ul class="navbar-nav flex-grow-1" style="flex-direction: inherit !important">
						<partial name="_loginPartial" />
					</ul>
				</div>
			</nav>
		</div>
	</header>
	<div class="container">
		<partial name="_CookieConsentPartial" />
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2019 - vBlogger
		</div>
	</footer>

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
	</environment>
	<environment exclude="Development">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
		</script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
		</script>
	</environment>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@RenderSection("Scripts", required: false)
</body>
</html>